import type { NextPage } from 'next'
import Head from 'next/head'
import HeaderBig from '../components/HeaderBig'
import styles from '../styles/Home.module.css'
import Image from 'next/image'
import { useState } from 'react'

const Home: NextPage = () => {
  return (
    <div className={styles.container}>  
      <Head>
        <title>Abstratica</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico"/>
      </Head>

      <HeaderBig />
      <h1 className='section-title text-shadow' id={styles["first-page-element"]}>
        The First GAN Art on Solana
      </h1>
      <div className='sub-container'>
        <div className={styles.carousel}>
          <p>This will be the carousel</p>
        </div>
      </div>

      <h1 className='section-title text-shadow'>
        Why Collect Abstractions
      </h1>

      <div className='sub-container wide-container'>
        <div className='text-box'>
          <p>Being the 1st ever GAN art project and the 9th overall project to mint on Solana, Abstratica is a <strong>piece of Solana history</strong>.</p>
        </div>
        <div className='text-box'>
          <p>Collecting Abstractions will <strong>give you exposure to the 1:1 art scenne</strong> without having to go digging for the next big artists yourself.</p>
        </div>
        <div className='text-box'>
          <p>Owning just 1 Abstraction allows you to <strong>access our in-discord printing service</strong>. You can print any NFT, in high quality and at affordable prices.</p>
        </div>
        <div className='text-box'>
          <p>Abstractions are beautiful.<br></br> WE LOVE THE ART!</p>
        </div>
      </div>

      <div className='sub-container'>
        <div className={styles["investor-box"]}>
          <h1 className='section-title black-text'>Notable Collectors</h1>
          <div className={styles["pfp-and-name"]}>
            <Image src={"/solbigbrain.jpg"} height={100} width={100} alt="solbigbrain"></Image>
            <p>SolBigBrain</p>
          </div>
          <div className={styles["pfp-and-name"]}>
            <Image src={"/grayscale.jpg"} height={100} width={100} alt="grayscale"></Image>
            <p>Grayscale</p>
          </div>
          <div className={styles["pfp-and-name"]}>
            <Image src={"/anglio.jpg"} height={100} width={100} alt="anglio"></Image>
            <p>Anglio</p>
          </div>
        </div>
      </div>
    </div>
  )
}

export default Home
